### ISSUE TITLE
WSA on Windows 10

### ISSUE THREAD

**Issue by Windows200000** [riverar/wsa-app-compatibility#264]
I use [this GitHub project](https://github.com/MustardChef/WSABuilds/releases/Windows_10_2303.40000.5.0) on Windows 10. It removes Amazon App Store, adds Google Play Store and Service and Magisk (for Root Access).

So far, I have encountered the same compatibility as listed on this website, but it's an older version of WSA as newer ones don't work on Win10 yet, and it's modified. I'd assume I shouldn't contribute, but it might be worth considering adding supported WSA versions or Win10.

**Comment by win98se** [comment]
https://github.com/MustardChef/WSABuilds/releases/tag/Windows_10_2305.40000.3.0
Latest version (2305.40000.3.0 as of this comment) of WSABuilds seem to work on Windows 10 again.

**Comment by pratyakshm** [comment]
I'm not sure if I correctly understood what you meant, but here are two possible interpretations and answers to them:

1. Add a note that WSA supports Windows 10.
We do not encourage using WSA on unsupported Windows versions, thus we won't be proceeding with this proposal.

2. Add WSA versions next to each compatibility entry.
This is a daunting task. Since WSA is continuously updated, I do not see a point in adding a separate versions column. Also, not all contributors will want to come back and update the column with each update.
